//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_Semana11_Lunes.ServicioNegocios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cliente", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idclienteField, value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecia {
            get {
                return this.nombreciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreciaField, value) != true)) {
                    this.nombreciaField = value;
                    this.RaisePropertyChanged("nombrecia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pais", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWCF")]
    [System.SerializableAttribute()]
    public partial class pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrepaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrepais {
            get {
                return this.nombrepaisField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrepaisField, value) != true)) {
                    this.nombrepaisField = value;
                    this.RaisePropertyChanged("nombrepais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioNegocios.IServicioContrato")]
    public interface IServicioContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Clientes", ReplyAction="http://tempuri.org/IServicioContrato/ClientesResponse")]
        WebSite_Semana11_Lunes.ServicioNegocios.cliente[] Clientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Clientes", ReplyAction="http://tempuri.org/IServicioContrato/ClientesResponse")]
        System.Threading.Tasks.Task<WebSite_Semana11_Lunes.ServicioNegocios.cliente[]> ClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Paises", ReplyAction="http://tempuri.org/IServicioContrato/PaisesResponse")]
        WebSite_Semana11_Lunes.ServicioNegocios.pais[] Paises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Paises", ReplyAction="http://tempuri.org/IServicioContrato/PaisesResponse")]
        System.Threading.Tasks.Task<WebSite_Semana11_Lunes.ServicioNegocios.pais[]> PaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/ClientesxPais", ReplyAction="http://tempuri.org/IServicioContrato/ClientesxPaisResponse")]
        WebSite_Semana11_Lunes.ServicioNegocios.cliente[] ClientesxPais(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/ClientesxPais", ReplyAction="http://tempuri.org/IServicioContrato/ClientesxPaisResponse")]
        System.Threading.Tasks.Task<WebSite_Semana11_Lunes.ServicioNegocios.cliente[]> ClientesxPaisAsync(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Agregar", ReplyAction="http://tempuri.org/IServicioContrato/AgregarResponse")]
        string Agregar(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Agregar", ReplyAction="http://tempuri.org/IServicioContrato/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Actualizar", ReplyAction="http://tempuri.org/IServicioContrato/ActualizarResponse")]
        string Actualizar(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Actualizar", ReplyAction="http://tempuri.org/IServicioContrato/ActualizarResponse")]
        System.Threading.Tasks.Task<string> ActualizarAsync(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Eliminar", ReplyAction="http://tempuri.org/IServicioContrato/EliminarResponse")]
        string Eliminar(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioContrato/Eliminar", ReplyAction="http://tempuri.org/IServicioContrato/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioContratoChannel : WebSite_Semana11_Lunes.ServicioNegocios.IServicioContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioContratoClient : System.ServiceModel.ClientBase<WebSite_Semana11_Lunes.ServicioNegocios.IServicioContrato>, WebSite_Semana11_Lunes.ServicioNegocios.IServicioContrato {
        
        public ServicioContratoClient() {
        }
        
        public ServicioContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebSite_Semana11_Lunes.ServicioNegocios.cliente[] Clientes() {
            return base.Channel.Clientes();
        }
        
        public System.Threading.Tasks.Task<WebSite_Semana11_Lunes.ServicioNegocios.cliente[]> ClientesAsync() {
            return base.Channel.ClientesAsync();
        }
        
        public WebSite_Semana11_Lunes.ServicioNegocios.pais[] Paises() {
            return base.Channel.Paises();
        }
        
        public System.Threading.Tasks.Task<WebSite_Semana11_Lunes.ServicioNegocios.pais[]> PaisesAsync() {
            return base.Channel.PaisesAsync();
        }
        
        public WebSite_Semana11_Lunes.ServicioNegocios.cliente[] ClientesxPais(string pais) {
            return base.Channel.ClientesxPais(pais);
        }
        
        public System.Threading.Tasks.Task<WebSite_Semana11_Lunes.ServicioNegocios.cliente[]> ClientesxPaisAsync(string pais) {
            return base.Channel.ClientesxPaisAsync(pais);
        }
        
        public string Agregar(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg) {
            return base.Channel.Agregar(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg) {
            return base.Channel.AgregarAsync(reg);
        }
        
        public string Actualizar(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg) {
            return base.Channel.Actualizar(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAsync(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg) {
            return base.Channel.ActualizarAsync(reg);
        }
        
        public string Eliminar(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg) {
            return base.Channel.Eliminar(reg);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(WebSite_Semana11_Lunes.ServicioNegocios.cliente reg) {
            return base.Channel.EliminarAsync(reg);
        }
    }
}
